version: '3.8'

services:
  gnas:
    image: tbma-gnas:latest
    command: bash
    tty: true
    stdin_open: true
    volumes:
      - ./tbma_gnas:/tbma_gnas
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
