version: '3.8'

services:
  gnas:
    image: tbma_gnas:latest
    command: bash
    tty: true
    stdin_open: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
